# Generated by Django 4.2 on 2023-06-13 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Collage', '0003_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attendee', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collage.student')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('week', models.IntegerField(default=1)),
                ('picture_1', models.ImageField(null=True, upload_to='images/')),
                ('picture_2', models.ImageField(null=True, upload_to='images/')),
                ('picture_3', models.ImageField(null=True, upload_to='images/')),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collage.courseinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.IntegerField(default=0)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collage.student')),
            ],
        ),
    ]
