# Generated by Django 4.2 on 2023-05-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_remove_attendance_status_attendance_attend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='count_absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='picture',
            field=models.ImageField(default='pro.png', upload_to='images/'),
        ),
    ]
