# Generated by Django 4.2 on 2023-05-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_attendance_count_absent_lecture_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='picture',
        ),
    ]
