# Generated by Django 4.2 on 2023-05-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_remove_lecture_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
